
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: closet_app_development
test: &test
  <<: *default
  database: closet_app_development

production:
  <<: *default
  database: closet_app_development
  username: closet_app
  password: <%= ENV['CLOSET_APP_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
